### ISSUE TITLE
Open-source the editor?

### ISSUE THREAD

**Issue by yunkot** [MarquitosPT/Tulip#6]
There is a request for editor's source code:
http://www.pascalgamedevelopment.com/showthread.php?32475-Pascal-eXtended-Library-(aka-Asphyre)-released!&p=148824&viewfull=1#post148824

Any chance to open-source it?

**Comment by MarquitosPT** [comment]
Hi,
I haven't been working on it since 2014, but no problem on sharing the editor as open source.

I will add it to GitHub.

Best Regards.
